language: node_js
branches:
  only:
  - develop
node_js:
- '10'
before_script:
- chmod +x ./scripts/deploy.sh
script: "./scripts/deploy.sh"
env:
  global:
  - secure: DcgFlqdmPNwlYM2clGdcZzwQ81nY2ukvPcorA6bUgX/tniJDKDBcEVl6IXPZxKk4OeRRestedMZTHN+s78k9utou2cBcUUDySQIuH1aGsiHs4PZbETnOoTJCS6Rj7o7qHDCXTtFRoJp1cAXykIdS0llxJCJu2TI5e7VwB/0FKzAZuKpV1k632H/yuMYt9Jzmvc4ekxWKyQYzArL4teXjx91RqAIey6Qg20v94HemqROVzR/a+iF8iWZ/MJg2p8J5fT7Yem7e/wWWIufZk7Gsu/QFDcWTrpuLu3ActyTMDppB29v11Qf/L+NhpQHOuWPFVYFTniG56fA0tT1NLD2NavCgHh2ZuYfyl13QqacVkas2VBs4YKW1hX+eXOxq/R53ZmVLmYsuUWwk6U+WUojhVOWM+N2uXjlEVwYKrLbIedIoEo0NjeqFDWY2T9bdxWUAe1L3S58U7IgTxIb/m/jvkhWNvqm3b8n17HObkOSBunEGvNOyvb/YguoS/2/B+wxaA0U3QjH0h40PC1ZUogyyf3GQ7tCFQw3CyyuO8YgwzavFoCeW8ZxZdev9f1ul17Fy/+HpOoHN9y7MnxOYnnELPD8EevXvvCafD9p8ck2g1b11EdNYtjZeKCh0yS3X4Vt26GufY2b0Wp7bWpDJLgKImzkEjEyNtGOSFUYxaWxUmr4=
